"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { formatCollectorTimestamp, groupCollectorLogs } from "@/collector/logRuns";
import type { AuditEntry, ManualSuspensionDraft } from "@/lib/admin/types";
import type { CollectorLog, CollectorSourceConfig, EducationLevel, SuspensionRecord } from "@/types";
import { Activity, AlertTriangle, CheckCircle2, Clock3, ExternalLink, FileCheck2, History, LogOut, Play, RefreshCw, RotateCcw, ShieldCheck, Terminal, Trash2, Undo2 } from "lucide-react";

type RegistryData = { lgus: { id: string; name: string }[]; schools: { id: string; name: string; campusName?: string; lguId: string; sector: "public" | "private"; levelsOffered: EducationLevel[] }[] };
type Bootstrap = { session: { csrfToken: string }; sources: CollectorSourceConfig[]; logs: CollectorLog[]; records: SuspensionRecord[]; audit: AuditEntry[]; auditTotal: number; registries: RegistryData };
type PublicationPreview = { normalizedDraft: ManualSuspensionDraft; confirmationToken: string; expiresAt: string; preview: { heading: string; scope: string; reason: string; effectiveDate: string; duration: string; evidence: string; proofUrl: string; publication: string } };
const LEVELS: { value: EducationLevel; label: string }[] = [["all-levels", "All Levels"], ["preschool", "Preschool"], ["elementary", "Elementary"], ["junior-high", "Junior High"], ["senior-high", "Senior High"], ["college", "College"], ["graduate", "Graduate"]].map(([value, label]) => ({ value: value as EducationLevel, label }));
const REASONS = [["heavy-rain", "Heavy Rain"], ["flooding", "Flooding"], ["typhoon", "Typhoon"], ["extreme-heat", "Extreme Heat"], ["earthquake", "Earthquake"], ["transport-disruption", "Transport Disruption"], ["emergency", "Emergency"], ["lgu-declaration", "LGU Declaration"], ["school-administration-announcement", "School Administration Announcement"], ["power-interruption", "Power Interruption"], ["water-interruption", "Water Interruption"], ["other", "Other"]];
const DURATIONS = [["whole-day", "Whole Day"], ["until-further-notice", "Until Further Notice"], ["morning-classes", "Morning Classes"], ["afternoon-classes", "Afternoon Classes"], ["evening-classes", "Evening Classes"], ["from-specific-time", "From Specific Time"], ["other", "Other"]];
const EVIDENCE = [["gma-news", "GMA News"], ["rappler", "Rappler"], ["lgu-official-announcement", "LGU Official Announcement"], ["school-official-announcement", "School Official Announcement"], ["deped", "DepEd"], ["ched", "CHED"], ["pagasa", "PAGASA"], ["other", "Other"]];

function manilaDate(offsetDays = 0) {
  const date = new Date(Date.now() + offsetDays * 86_400_000); const parts = new Intl.DateTimeFormat("en-US", { timeZone: "Asia/Manila", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(date);
  const part = (type: string) => parts.find((item) => item.type === type)?.value; return `${part("year")}-${part("month")}-${part("day")}`;
}
function freshDraft(): ManualSuspensionDraft { return { targetType: "lgu", targetId: "caloocan", sector: "all", affectedLevels: ["all-levels"], effectiveDate: manilaDate(), reason: { preset: "heavy-rain" }, duration: { preset: "whole-day", isAllDay: true }, evidence: { preset: "lgu-official-announcement" }, proofUrl: "", publicNote: "" }; }
function uuid() { return crypto.randomUUID(); }

export function AdminConsoleClient() {
  const router = useRouter(); const [data, setData] = useState<Bootstrap | null>(null); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState("");
  const [draft, setDraft] = useState<ManualSuspensionDraft>(freshDraft); const [preview, setPreview] = useState<PublicationPreview | null>(null); const [removeRecord, setRemoveRecord] = useState<SuspensionRecord | null>(null);
  const [selectedRunId, setSelectedRunId] = useState<string | null>(null); const logViewport = useRef<HTMLDivElement>(null); const previewBackRef = useRef<HTMLButtonElement>(null); const removeCancelRef = useRef<HTMLButtonElement>(null); const [now, setNow] = useState(Date.now());
  const load = useCallback(async () => {
    const response = await fetch("/api/admin/bootstrap", { cache: "no-store" });
    if (response.status === 401) { router.replace("/collector/login"); return; }
    if (!response.ok) throw new Error("The Admin Console is unavailable. Check secure storage and authentication configuration.");
    setData(await response.json());
  }, [router]);
  useEffect(() => { load().catch((reason) => setError(reason.message)); const poll = window.setInterval(() => load().catch(() => undefined), 10_000); const tick = window.setInterval(() => setNow(Date.now()), 1000); return () => { clearInterval(poll); clearInterval(tick); }; }, [load]);
  useEffect(() => { if (preview) previewBackRef.current?.focus(); else if (removeRecord) removeCancelRef.current?.focus(); const close = (event: KeyboardEvent) => { if (event.key === "Escape") { setPreview(null); setRemoveRecord(null); } }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [preview, removeRecord]);
  const mutate = async (url: string, body: unknown) => {
    if (!data) throw new Error("Admin session is not ready.");
    const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json", "X-CSRF-Token": data.session.csrfToken }, body: JSON.stringify(body) });
    const result = await response.json().catch(() => ({})); if (response.status === 401) { router.replace("/collector/login"); throw new Error("Your session expired."); } if (!response.ok) throw new Error(result.error || "The request was rejected."); return result;
  };
  const logRuns = useMemo(() => groupCollectorLogs(data?.logs || []), [data?.logs]); const selectedRun = logRuns.find((run) => run.id === selectedRunId) || logRuns[0];
  const activeRecords = (data?.records || []).filter((record) => record.administrativeState !== "pending_removal");
  const pendingRecords = (data?.records || []).filter((record) => record.administrativeState === "pending_removal" && record.undoDeadline && Date.parse(record.undoDeadline) > now);
  const targetLabel = (record: SuspensionRecord) => record.schoolId ? data?.registries.schools.find((item) => item.id === record.schoolId)?.name || record.schoolId : data?.registries.lgus.find((item) => item.id === record.lguId)?.name || record.lguId;
  const fieldClass = "min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-base text-slate-900 outline-none focus:ring-2 focus:ring-blue-500 dark:border-slate-700 dark:bg-slate-950 dark:text-white";
  const timed = ["morning-classes", "afternoon-classes", "evening-classes", "from-specific-time"].includes(draft.duration.preset) || (draft.duration.preset === "other" && draft.duration.isAllDay !== true);
  const selectedSchool = data?.registries.schools.find((school) => school.id === draft.targetId);
  async function runCollector() { setBusy("collector"); setError(""); try { const result = await mutate("/api/collector/run", {}); setNotice(`Collector finished: ${result.summary.announcementsPublished} published, ${result.summary.announcementsHeld} held, ${result.summary.announcementsRejected} rejected.`); await load(); setSelectedRunId(null); requestAnimationFrame(() => logViewport.current?.scrollTo({ top: 0 })); } catch (reason) { setError(reason instanceof Error ? reason.message : "Collector run failed."); } finally { setBusy(""); } }
  async function requestPreview(event: React.FormEvent) { event.preventDefault(); setBusy("preview"); setError(""); try { setPreview(await mutate("/api/admin/suspensions/preview", draft)); } catch (reason) { setError(`Preview rejected: ${reason instanceof Error ? reason.message : "validation failed"}`); } finally { setBusy(""); } }
  async function publish() { if (!preview) return; setBusy("publish"); try { await mutate("/api/admin/suspensions", { draft: preview.normalizedDraft, confirmationToken: preview.confirmationToken, idempotencyKey: uuid(), confirmed: true }); setPreview(null); setDraft(freshDraft()); setNotice("Suspension published to the live ClassStatus view."); await load(); } catch (reason) { setError(`Publication rejected: ${reason instanceof Error ? reason.message : "request failed"}`); } finally { setBusy(""); } }
  async function remove() { if (!removeRecord) return; setBusy("remove"); try { await mutate(`/api/admin/suspensions/${removeRecord.id}/remove`, { expectedRevision: removeRecord.revision || 1, idempotencyKey: uuid(), confirmed: true }); setRemoveRecord(null); setNotice("Suspension removed from public status. Undo is available for 30 seconds."); await load(); } catch (reason) { setError(`Removal rejected: ${reason instanceof Error ? reason.message : "request failed"}`); } finally { setBusy(""); } }
  async function undo(record: SuspensionRecord) { setBusy(`undo-${record.id}`); try { await mutate(`/api/admin/suspensions/${record.id}/undo`, { expectedRevision: record.revision || 1, idempotencyKey: uuid() }); setNotice("Removal undone. The original suspension is active again."); await load(); } catch (reason) { setError(`Undo rejected: ${reason instanceof Error ? reason.message : "request failed"}`); await load(); } finally { setBusy(""); } }
  async function logout() { setBusy("logout"); try { await mutate("/api/admin/auth/logout", {}); router.replace("/collector/login"); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Logout failed."); } finally { setBusy(""); } }
  async function loadMoreAudit() { if (!data) return; const page = Math.floor(data.audit.length / 50) + 1; const response = await fetch(`/api/admin/audit?page=${page}&limit=50`, { cache: "no-store" }); if (!response.ok) { setError("Could not load more audit history."); return; } const payload = await response.json(); setData({ ...data, audit: [...data.audit, ...payload.entries], auditTotal: payload.total }); }

  return <div className="min-h-screen flex flex-col"><Navbar /><main className="mx-auto w-full max-w-7xl flex-1 space-y-8 px-4 py-8 sm:px-6 lg:px-8">
    <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="mb-2 flex items-center gap-2 text-sm font-bold text-blue-700 dark:text-blue-300"><ShieldCheck className="h-4 w-4" />Authenticated administrator</div><h1 className="text-3xl font-extrabold tracking-tight text-slate-950 dark:text-white sm:text-4xl">ClassStatus Admin Console</h1><p className="mt-2 max-w-2xl text-sm text-slate-600 dark:text-slate-400">Publish verified notices, manage live records, and inspect Rappler/GMA collector health.</p></div><button onClick={logout} disabled={busy === "logout"} className="flex min-h-11 items-center justify-center gap-2 rounded-xl border border-slate-300 px-4 text-sm font-bold text-slate-700 hover:bg-slate-100 dark:border-slate-700 dark:text-slate-200 dark:hover:bg-slate-800"><LogOut className="h-4 w-4" />Logout</button></header>
    {(error || notice) && <div role="status" className={`flex items-start justify-between gap-3 rounded-xl border px-4 py-3 text-sm ${error ? "border-red-200 bg-red-50 text-red-800 dark:border-red-900 dark:bg-red-950 dark:text-red-200" : "border-emerald-200 bg-emerald-50 text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950 dark:text-emerald-200"}`}><span>{error || notice}</span><button onClick={() => { setError(""); setNotice(""); }} className="font-bold">Dismiss</button></div>}
    {!data ? <div className="py-24 text-center text-sm text-slate-500">Loading secure console…</div> : <>
      <section aria-labelledby="overview-title" className="space-y-3"><div className="flex items-center justify-between"><h2 id="overview-title" className="text-xl font-bold text-slate-950 dark:text-white">Overview</h2><button onClick={() => load().catch((reason) => setError(reason.message))} className="flex items-center gap-1.5 text-sm font-semibold text-blue-600"><RefreshCw className="h-4 w-4" />Refresh</button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <Overview label="Operational sources" value={`${data.sources.length}`} detail="Rappler and GMA News" icon={<ShieldCheck />} />
        <Overview label="Source health" value={`${data.sources.filter((s) => s.healthStatus === "healthy" || s.healthStatus === "reachable_no_candidates").length}/${data.sources.length}`} detail={data.sources.map((s) => `${s.organization}: ${(s.healthStatus || "not checked").replaceAll("_", " ")}`).join(" · ")} icon={<Activity />} />
        <Overview label="Latest collector run" value={logRuns[0] ? formatCollectorTimestamp(logRuns[0].startedAt) : "No run yet"} detail={logRuns[0]?.summary || "Awaiting a collector execution"} icon={<Clock3 />} />
        <Overview label="Current suspensions" value={`${activeRecords.length}`} detail={`${pendingRecords.length} pending removal`} icon={<FileCheck2 />} />
      </div></section>
      {pendingRecords.length > 0 && <section aria-label="Undo removals" className="space-y-2">{pendingRecords.map((record) => <div key={record.id} className="flex flex-col justify-between gap-3 rounded-xl border border-amber-300 bg-amber-50 px-4 py-3 text-amber-950 dark:border-amber-800 dark:bg-amber-950 dark:text-amber-100 sm:flex-row sm:items-center"><div><strong>{targetLabel(record)}</strong> is no longer public. Undo closes in <span className="font-mono font-bold">{Math.max(0, Math.ceil((Date.parse(record.undoDeadline!) - now) / 1000))}s</span>.</div><button onClick={() => undo(record)} disabled={busy === `undo-${record.id}`} className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-amber-900 px-4 text-sm font-bold text-white disabled:opacity-60"><Undo2 className="h-4 w-4" />Undo removal</button></div>)}</section>}
      <section aria-labelledby="current-title" className="space-y-3"><div><h2 id="current-title" className="text-xl font-bold text-slate-950 dark:text-white">Current Suspensions</h2><p className="mt-1 text-sm text-slate-500">Active and upcoming publications. Removal preserves evidence and audit history.</p></div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900">{activeRecords.length === 0 ? <p className="px-5 py-10 text-center text-sm text-slate-500">No active suspension records.</p> : activeRecords.map((record) => <article key={record.id} className="flex flex-col gap-4 border-b border-slate-100 p-4 last:border-0 dark:border-slate-800 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold text-slate-950 dark:text-white">{targetLabel(record)}</h3><span className="rounded-md bg-slate-100 px-2 py-0.5 text-[11px] font-bold uppercase text-slate-600 dark:bg-slate-800 dark:text-slate-300">{record.schoolId ? "School" : "LGU"}</span><span className="rounded-md bg-blue-50 px-2 py-0.5 text-[11px] font-bold text-blue-700 dark:bg-blue-950 dark:text-blue-300">{record.publicationProvenance?.type === "manual-admin" ? "Manual admin" : "Automatic collector"}</span></div><p className="mt-1 text-sm text-slate-700 dark:text-slate-300">{record.reason} · {record.durationLabel || (record.isAllDay ? "Whole Day" : `${record.startTime}–${record.endTime}`)}</p><p className="mt-1 text-xs text-slate-500">{record.effectiveDate} · {record.affectedLevels.join(", ")} · {record.schoolSector} · {record.source.organization}</p><a href={record.manualEvidence?.proofUrl || record.source.url} target="_blank" rel="noopener noreferrer" className="mt-1 inline-flex items-center gap-1 text-xs font-semibold text-blue-600">View evidence <ExternalLink className="h-3 w-3" /></a></div><button onClick={() => setRemoveRecord(record)} className="flex min-h-11 shrink-0 items-center justify-center gap-2 rounded-xl border border-red-200 px-4 text-sm font-bold text-red-700 hover:bg-red-50 dark:border-red-900 dark:text-red-300 dark:hover:bg-red-950"><Trash2 className="h-4 w-4" />Remove</button></article>)}</div></section>
      <section aria-labelledby="publish-title" className="space-y-3"><div><h2 id="publish-title" className="text-xl font-bold text-slate-950 dark:text-white">Publish Suspension</h2><p className="mt-1 text-sm text-slate-500">Registry-backed, evidence-required manual publication.</p></div><form onSubmit={requestPreview} className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900 sm:grid-cols-2 sm:p-6">
        <Field label="Target type"><select className={fieldClass} value={draft.targetType} onChange={(e) => { const targetType = e.target.value as "lgu" | "school"; const first = targetType === "lgu" ? data.registries.lgus[0].id : data.registries.schools[0].id; setDraft({ ...draft, targetType, targetId: first, sector: targetType === "lgu" ? "all" : data.registries.schools[0].sector, affectedLevels: ["all-levels"] }); setPreview(null); }}><option value="lgu">LGU</option><option value="school">School</option></select></Field>
        <Field label="Target"><select className={fieldClass} value={draft.targetId} onChange={(e) => { const school = data.registries.schools.find((item) => item.id === e.target.value); setDraft({ ...draft, targetId: e.target.value, ...(school ? { sector: school.sector } : {}) }); setPreview(null); }}>{(draft.targetType === "lgu" ? data.registries.lgus : data.registries.schools).map((item) => <option key={item.id} value={item.id}>{item.name}{"campusName" in item && item.campusName ? ` — ${item.campusName}` : ""}</option>)}</select></Field>
        <Field label="Sector"><select className={fieldClass} value={selectedSchool?.sector || draft.sector} disabled={draft.targetType === "school"} onChange={(e) => setDraft({ ...draft, sector: e.target.value as ManualSuspensionDraft["sector"] })}><option value="all">Public + Private</option><option value="public">Public</option><option value="private">Private</option></select></Field>
        <Field label="Class level"><select className={fieldClass} value={draft.affectedLevels[0]} onChange={(e) => setDraft({ ...draft, affectedLevels: [e.target.value as EducationLevel] })}>{LEVELS.filter((level) => !selectedSchool || level.value === "all-levels" || selectedSchool.levelsOffered.includes(level.value)).map((level) => <option key={level.value} value={level.value}>{level.label}</option>)}</select></Field>
        <Field label="Effective date"><div className="grid grid-cols-3 gap-2"><button type="button" onClick={() => setDraft({ ...draft, effectiveDate: manilaDate() })} className={`min-h-11 rounded-xl border text-sm font-bold ${draft.effectiveDate === manilaDate() ? "border-blue-600 bg-blue-600 text-white" : "border-slate-300 dark:border-slate-700"}`}>Today</button><button type="button" onClick={() => setDraft({ ...draft, effectiveDate: manilaDate(1) })} className={`min-h-11 rounded-xl border text-sm font-bold ${draft.effectiveDate === manilaDate(1) ? "border-blue-600 bg-blue-600 text-white" : "border-slate-300 dark:border-slate-700"}`}>Tomorrow</button><input aria-label="Custom effective date" type="date" min={manilaDate()} max={manilaDate(1)} value={draft.effectiveDate} onChange={(e) => setDraft({ ...draft, effectiveDate: e.target.value })} className={fieldClass} /></div></Field>
        <PresetField label="Suspension reason" options={REASONS} value={draft.reason} onChange={(reason) => setDraft({ ...draft, reason })} customLabel="Specify reason" fieldClass={fieldClass} />
        <PresetField label="Duration / applicable time" options={DURATIONS} value={draft.duration} onChange={(duration) => setDraft({ ...draft, duration: { ...duration, isAllDay: duration.preset === "whole-day" || duration.preset === "until-further-notice" } })} customLabel="Specify duration / applicable time" fieldClass={fieldClass} />
        {draft.duration.preset === "other" && <label className="flex min-h-11 items-center gap-2 text-sm font-semibold text-slate-700 dark:text-slate-300"><input type="checkbox" checked={draft.duration.isAllDay === true} onChange={(event) => setDraft({ ...draft, duration: { ...draft.duration, isAllDay: event.target.checked, ...(event.target.checked ? { startTime: undefined, endTime: undefined } : {}) } })} className="h-4 w-4 rounded border-slate-300 text-blue-600" />Apply for the whole day</label>}
        {timed && <div className="grid grid-cols-2 gap-2"><Field label="Start time"><input required type="time" className={fieldClass} value={draft.duration.startTime || ""} onChange={(e) => setDraft({ ...draft, duration: { ...draft.duration, startTime: e.target.value } })} /></Field><Field label="End time"><input required type="time" className={fieldClass} value={draft.duration.endTime || ""} onChange={(e) => setDraft({ ...draft, duration: { ...draft.duration, endTime: e.target.value } })} /></Field></div>}
        <PresetField label="Evidence source/provider" options={EVIDENCE} value={draft.evidence} onChange={(evidence) => setDraft({ ...draft, evidence })} customLabel="Specify evidence source" fieldClass={fieldClass} />
        <Field label="Proof URL"><input required type="url" maxLength={2048} placeholder="https://…" className={fieldClass} value={draft.proofUrl} onChange={(e) => setDraft({ ...draft, proofUrl: e.target.value })} /></Field>
        <Field label="Optional public note" wide><textarea maxLength={500} rows={3} className={`${fieldClass} py-2.5`} value={draft.publicNote || ""} onChange={(e) => setDraft({ ...draft, publicNote: e.target.value })} /></Field>
        <div className="sm:col-span-2 flex justify-end"><button disabled={busy === "preview"} className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 text-sm font-bold text-white hover:bg-blue-700 disabled:opacity-60"><FileCheck2 className="h-4 w-4" />{busy === "preview" ? "Validating…" : "Review publication"}</button></div>
      </form></section>
      <section aria-labelledby="diagnostics-title" className="space-y-3"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 id="diagnostics-title" className="text-xl font-bold text-slate-950 dark:text-white">Collector Diagnostics</h2><p className="mt-1 text-sm text-slate-500">Authenticated Rappler and GMA execution history.</p></div><button onClick={runCollector} disabled={busy === "collector"} className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-bold text-white disabled:opacity-60">{busy === "collector" ? <RefreshCw className="h-4 w-4 animate-spin" /> : <Play className="h-4 w-4" />}{busy === "collector" ? "Running…" : "Run collector"}</button></div><div className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-950 font-mono text-xs text-slate-100"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-800 px-4 py-3"><div><span className="rounded-md border border-blue-800 bg-blue-950 px-2 py-1 text-[10px] font-bold uppercase text-blue-300">{selectedRun === logRuns[0] ? "Latest run" : "Historical run"}</span><span className="ml-2 text-[11px] text-slate-400">{selectedRun ? formatCollectorTimestamp(selectedRun.startedAt) : "No runs"}</span></div>{logRuns.length > 1 && <select value={selectedRun?.id} onChange={(e) => { setSelectedRunId(e.target.value); requestAnimationFrame(() => logViewport.current?.scrollTo({ top: 0 })); }} className="rounded-md border border-slate-700 bg-slate-900 px-2 py-1 text-[11px]"><option value={logRuns[0].id}>Latest — {formatCollectorTimestamp(logRuns[0].startedAt)}</option>{logRuns.slice(1).map((run) => <option key={run.id} value={run.id}>History — {formatCollectorTimestamp(run.startedAt)}</option>)}</select>}</div><div ref={logViewport} className="max-h-96 space-y-2 overflow-auto p-4">{!selectedRun ? <p className="py-10 text-center text-slate-500">No collector logs recorded.</p> : selectedRun.logs.map((log) => <div key={log.id} className="flex items-start gap-2.5 leading-relaxed"><span className="shrink-0 pt-0.5 text-[10px] text-slate-500">{formatCollectorTimestamp(log.timestamp)}</span><span className={`shrink-0 rounded border px-1.5 text-[10px] font-bold uppercase ${log.level === "success" ? "border-emerald-800 bg-emerald-950 text-emerald-400" : log.level === "error" ? "border-red-800 bg-red-950 text-red-400" : log.level === "warn" ? "border-amber-800 bg-amber-950 text-amber-400" : "border-blue-800 bg-blue-950 text-blue-400"}`}>{log.level}</span><span className="overflow-wrap-anywhere text-slate-300"><strong className="text-slate-100">[{log.sourceName}]</strong> {log.message}</span></div>)}</div></div></section>
      <section aria-labelledby="activity-title" className="space-y-3"><div><h2 id="activity-title" className="text-xl font-bold text-slate-950 dark:text-white">Admin Activity</h2><p className="mt-1 text-sm text-slate-500">Append-oriented security and publication history.</p></div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900">{data.audit.length === 0 ? <p className="p-8 text-center text-sm text-slate-500">No admin activity recorded.</p> : data.audit.map((entry) => <div key={entry.id} className="flex items-start gap-3 border-b border-slate-100 px-4 py-3 text-sm last:border-0 dark:border-slate-800"><History className="mt-0.5 h-4 w-4 shrink-0 text-slate-400" /><div><div className="font-semibold text-slate-900 dark:text-white">{entry.action.replaceAll("-", " ")} · {entry.outcome}</div><div className="text-xs text-slate-500">{new Intl.DateTimeFormat("en-US", { timeZone: "Asia/Manila", dateStyle: "medium", timeStyle: "medium" }).format(new Date(entry.timestamp))} PHT{entry.targetSummary ? ` · ${entry.targetSummary}` : ""}</div></div></div>)}{data.audit.length < data.auditTotal && <div className="p-3 text-center"><button onClick={loadMoreAudit} className="min-h-11 rounded-xl border border-slate-300 px-4 text-sm font-bold dark:border-slate-700">Load older activity</button></div>}</div></section>
    </>}
  </main><Footer />
  {preview && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 p-4" role="dialog" aria-modal="true" aria-labelledby="preview-title"><div className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-2xl dark:bg-slate-900 sm:p-6"><h2 id="preview-title" className="text-xl font-bold text-slate-950 dark:text-white">Confirm publication</h2><div className="mt-4 space-y-2 rounded-xl bg-slate-50 p-4 text-sm dark:bg-slate-950"><h3 className="text-lg font-bold">{preview.preview.heading}</h3><p>{preview.preview.scope}</p><p><strong>Reason:</strong> {preview.preview.reason}</p><p><strong>Effective:</strong> {preview.preview.effectiveDate}</p><p><strong>Duration:</strong> {preview.preview.duration}</p><p><strong>Evidence:</strong> {preview.preview.evidence}</p><a href={preview.preview.proofUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 font-semibold text-blue-600">View proof <ExternalLink className="h-3 w-3" /></a><p className="font-semibold text-emerald-700 dark:text-emerald-300">{preview.preview.publication}</p></div><div className="mt-5 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button ref={previewBackRef} onClick={() => setPreview(null)} className="min-h-11 rounded-xl border border-slate-300 px-4 text-sm font-bold dark:border-slate-700">Back and edit</button><button onClick={publish} disabled={busy === "publish"} className="min-h-11 rounded-xl bg-blue-600 px-5 text-sm font-bold text-white disabled:opacity-60">{busy === "publish" ? "Publishing…" : "Confirm and publish"}</button></div></div></div>}
  {removeRecord && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 p-4" role="dialog" aria-modal="true" aria-labelledby="remove-title"><div className="w-full max-w-md rounded-2xl bg-white p-5 shadow-2xl dark:bg-slate-900"><AlertTriangle className="h-7 w-7 text-red-600" /><h2 id="remove-title" className="mt-3 text-xl font-bold">Remove this suspension?</h2><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">Are you sure you want to remove this suspension from the live map?</p><div className="mt-4 rounded-xl bg-slate-50 p-3 text-sm dark:bg-slate-950"><strong>{targetLabel(removeRecord)}</strong><p>{removeRecord.reason} · {removeRecord.effectiveDate}</p><p className="text-xs text-slate-500">{removeRecord.source.organization} · revision {removeRecord.revision || 1}</p></div><p className="mt-3 text-xs text-slate-500">The record becomes inactive immediately. Undo is available for exactly 30 seconds.</p><div className="mt-5 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button ref={removeCancelRef} onClick={() => setRemoveRecord(null)} className="min-h-11 rounded-xl border border-slate-300 px-4 text-sm font-bold dark:border-slate-700">Cancel</button><button onClick={remove} disabled={busy === "remove"} className="min-h-11 rounded-xl bg-red-600 px-4 text-sm font-bold text-white disabled:opacity-60">{busy === "remove" ? "Removing…" : "Remove from live map"}</button></div></div></div>}
  </div>;
}

function Overview({ label, value, detail, icon }: { label: string; value: string; detail: string; icon: React.ReactNode }) { return <div className="min-w-0 rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between gap-2 text-sm font-semibold text-slate-500"><span>{label}</span><span className="[&>svg]:h-4 [&>svg]:w-4">{icon}</span></div><div className="mt-2 text-2xl font-black text-slate-950 dark:text-white">{value}</div><p className="mt-1 overflow-hidden text-ellipsis text-xs text-slate-500">{detail}</p></div>; }
function Field({ label, children, wide = false }: { label: string; children: React.ReactNode; wide?: boolean }) { return <label className={`block min-w-0 text-sm font-semibold text-slate-800 dark:text-slate-200 ${wide ? "sm:col-span-2" : ""}`}><span className="mb-1.5 block">{label}</span>{children}</label>; }
function PresetField({ label, options, value, onChange, customLabel, fieldClass }: { label: string; options: string[][]; value: { preset: string; customValue?: string }; onChange: (value: { preset: string; customValue?: string }) => void; customLabel: string; fieldClass: string }) { return <div className="space-y-2"><Field label={label}><select className={fieldClass} value={value.preset} onChange={(e) => onChange({ preset: e.target.value })}>{options.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></Field>{value.preset === "other" && <label className="block text-xs font-semibold text-slate-600 dark:text-slate-400">{customLabel}<input required maxLength={120} className={`${fieldClass} mt-1`} value={value.customValue || ""} onChange={(e) => onChange({ preset: "other", customValue: e.target.value })} /></label>}</div>; }
